spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/khssna_wa7d
spring.datasource.username=khssna_user
spring.datasource.password=dev_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true